### ISSUE TITLE
EOF Tests : Test in line 103, should fail 

### ISSUE THREAD

**Issue by Demuirgos** [holiman/txparse#1]
line 103 : ``0xef000103000401000801000201000801000200303030303030303030303000300030303030303030003000``
the typesection size is exactly 2 * code-sections-count, so the expected number of code sections is 2 and not 4
which means typesection size should be 8
```
ef00 // magic code

01 // version

03 // type-section-kind
0004 // type-section-size = 2 * code-section-count

01 // code-section-kind
0008 // code-section-size

01 // code-section-kind
0002 // code-section-size

01 // code-section-kind
0008 // code-section-size

01 // code-section-kind
0002 // code-section-size

00 // header-terminator

3030 3030 // typesection

3030303030303000 // code section1
3000 // code section2
3030303030303000 // code section3
3000 // code section4
```

**Comment by holiman** [comment]
Nice! However, this ticket doesn't really belong here, but rather on the go-ethereum PR that `txparse` is based on. cc @lightclient

https://github.com/holiman/txparse/blob/main/eofparse/all.input#L103

**Comment by holiman** [comment]
I followed your profile, found https://github.com/NethermindEth/EOF-Header-Parser  -- nice!

**Comment by holiman** [comment]
Btw, what output do you get for that particular input?

**Comment by Demuirgos** [comment]
the errors in our impl are still being updated to be meaningful, so they are still "bad",  but it goes like this 
```
Err EIP-3540 : CodeSection count must match TypeSection suggested count
```

**Comment by holiman** [comment]
Thanks! Just a note though, spiting out `err: ` is the only 'mandatory' part of the error-output: 

> Otherwise, it outputs `err: ` and a suitable error message.

(so please make it lowercase and add colon)

**Comment by holiman** [comment]
cc @chfast fyi

**Comment by Demuirgos** [comment]
Noted, thanks

**Comment by lightclient** [comment]
Fixed in https://github.com/ethereum/go-ethereum/pull/26133/commits/43133d5693a945d4f412983163cd4fb8c4f88bd3

**Comment by holiman** [comment]
> Fixed in https://github.com/ethereum/go-ethereum/commit/43133d5693a945d4f412983163cd4fb8c4f88bd3

Confirmed: 

```
$ echo "0xef000103000401000801000201000801000200303030303030303030303000300030303030303030003000" | ./eofparse 
err: invalid type section size
```
Updated `all.output`

**Comment by holiman** [comment]
I also ran the fuzzer on the new code a bit, it found some new interesting inputs which have been added to `all.input` /`all.output`
